CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  secret TEXT,
  avatar VARCHAR(255),
  role VARCHAR(20) NOT NULL DEFAULT 'user'
);
